name: Mounts
version: 1.0
author: MCK
api-version: 1.12
main: me.therealmck.mounts.Main
commands:
  mounts:
    description: Mounts command
    usage: /mounts give [player] [type]
    permission: mounts.admin